version: '3.8'
services:
  dev-db:
    image: mysql:8.0.36
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_api
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    restart: always
    networks:
      - backend
  test-db:
    image: mysql:8.0.36
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_api
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    restart: always
    networks:
      - backend
networks:
  backend:
